server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:5173' # 허용하려는 도메인
            allow-credentials: true # 요청 시 인증 정보를 전송하도록 허가
            allowedHeaders: '*' # 허용하려는 헤더
            allowedMethods: # 허용하려는 HTTP 메서드
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: main-client
          uri: lb://MAIN-CLIENT
          predicates:
            - Path=/main-client/**
          filters:
            - RewritePath=/main-client/(?<segment>.*), /$\{segment}
            - JwtTokenFilter

        - id: member-client2
          uri: lb://MEMBER-CLIENT
          predicates:
            - Path=/member-client/member/member,/member-client/login
            - Method=POST
          filters:
            - RewritePath=/member-client/(?<segment>.*), /$\{segment}

        - id: member-client
          uri: lb://MEMBER-CLIENT
          predicates:
            - Path=/member-client/**
          filters:
            - RewritePath=/member-client/(?<segment>.*), /$\{segment}
            - JwtTokenFilter


#        - id: test-client
#          uri: lb://TEST-CLIENT
#          predicates:
#            - Path=/test-client/**
#          filters:
#            - RewritePath=/test-client/(?<segment>.*), /$\{segment}


token:
  secret: v7o98gdK42iddFqTxH07Yjv18KbwIZWQZu7NRPeR9+ji9tOGDX2r8PO3mGptklEdEiIB0RMT066q3qb19YBfqQ==
  expiration_time: 43200000 # 12시간
