server:
  port: 8081
spring:
  application:
    name: member-client
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.cbgyygo0sg4k.ap-southeast-2.rds.amazonaws.com:3306/MountainSpirit?&rewriteBatchedStatements=true
    username: admin
    password: bughunterbug
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    hibernate:    # 쿼리가 자동으로 소문자 + 스네이크로 변경되서 생성되지 않도록 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        '[format_sql]': true

  # 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB         # 업로드 할 수 있는 각 파일 용량(default 1MB)
      max-request-size: 200MB      # 업로드 요청당 총 용량(default 10MB)
  web:
    resources:
      static-locations: file:///C:/uploadFiles/     # 정적 리소스 경로
      cache-period: 3600                            # 웹 브라우저의 캐싱 시간(초, 1시간)

filepath: C:/uploadFiles


logging:
  level:
    com:
      ohgiraffers:
        springdatajpa: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


govermentData:
  serviceKey: 7a162b2698e08c06f13a25c9fe96fd89c1788751a7d3adc46918921e9ee2e2a5
  path:
    peakPoint: https://apis.data.go.kr/B553662/peakPoiInfoService/getPeakPoiInfoList
    mountain: https://apis.data.go.kr/B553662/top100FamtListBasiInfoService/getTop100FamtListBasiInfoList

token:
  secret: v7o98gdK42iddFqTxH07Yjv18KbwIZWQZu7NRPeR9+ji9tOGDX2r8PO3mGptklEdEiIB0RMT066q3qb19YBfqQ==
  expiration_time: 43200000 # 12시간

