server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: admin-service
          uri: http://localhost:8083
          predicates:
            - Path=/admin/**
        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report/**